import React, { Component } from "react";
import logo from "./logo.svg";
import "./App.css";
import { combineReducers, createStore } from "redux";
import { Provider, connect } from "react-redux";

// Redux code
// Redux state
// {
//   message:v (v is generated by the fn below)
// }

const UPDATE_MESSAGE = "UPDATE_MESSAGE";
const message = (state = "Hi from Redux and Ciao", action) => {
  switch (action.type) {
    case UPDATE_MESSAGE:
      return action.payload;
    default:
      return state;
  }
};

const rootReducer = combineReducers({
  message
});

const store = createStore(
  rootReducer,
  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
);

console.log("Store: ", store);
console.log("Store state : ", store.getState());

// React code
const CountWords = ({ message }) => (
  <p>There are {message.split(" ").filter(Boolean).length} words</p>
);

const CountCoffees = ({ message }) => (
  <p>
    You drank
    {
      message
        .split(" ")
        .filter(Boolean)
        .filter(w => w === "espresso").length
    }
    espressos
  </p>
);

const mapStateToProps = ({ message }) => ({ message });

const mapDispatchToProps = dispatch => {
  return {
    dispatchUpdateMessage: message => {
      const action = {
        type: UPDATE_MESSAGE,
        payload: message
      };
      dispatch(action);
    }
  };
};

const ConnectMessagePropToComponent = connect(
  mapStateToProps,
  mapDispatchToProps
);

const ConnectedCountWords = ConnectMessagePropToComponent(CountWords);

const ConnectedCountCoffees = ConnectMessagePropToComponent(CountCoffees);

class App extends Component {
  // state = {
  //   message: "Ciao"
  // };

  handleChange = ({ target: { value } }) => {
    // no longer used this.setState({ message: e.target.value });
    // this fn needs to update the redux state

    // 1. generate action
    // const action = {
    //   type: "UPDATE_MESSAGE",
    //   payload: value
    // };

    // 2. dispatch action
    //store.dispatch(action);
    this.props.dispatchUpdateMessage(value);
  };

  render() {
    const {
      props: { message }
    } = this;
    return (
      <>
        <input type="text" value={message} onChange={this.handleChange} />

        <p>The message is: {message}</p>
        <ConnectedCountWords />
        <ConnectedCountCoffees />
      </>
    );
  }
}

const ConnectedApp = ConnectMessagePropToComponent(App);

const Container = props => (
  <Provider store={store}>
    <ConnectedApp />
  </Provider>
);

export default Container;
